locals {
  location_slug = lookup(zipmap(values(local.regions), keys(local.regions)), var.azure_region, lookup(zipmap(values(local.cli_names), keys(local.cli_names)), var.azure_region, var.azure_region))
  regions = {
    us-west          = "West US"
    us-west-2        = "West US 2"
    us-west-3        = "West US 3"
    us-central       = "Central US"
    us-west-central  = "West Central US"
    us-south-central = "South Central US"
    us-north-central = "North Central US"
    us-east          = "East US"
    us-east-2        = "East US 2"
    can-central      = "Canada Central"
    can-east         = "Canada East"
    bra-south        = "Brazil South"
    bra-south-east   = "Brazil Southeast"
    uk-south         = "UK South"
    uk-west          = "UK West"
    eu-north         = "North Europe"
    eu-west          = "West Europe"
    fr-central       = "France Central"
    fr-south         = "France South"
    ger-north        = "Germany North"
    ger-north-east   = "Germany Northeast"
    ger-central      = "Germany Central"
    ger-west-central = "Germany West Central"
    swz-north        = "Switzerland North"
    swz-west         = "Switzerland West"
    norw-east        = "Norway East"
    norw-west        = "Norway West"
    saf-west         = "South Africa West"
    saf-north        = "South Africa North"
    ind-west         = "West India"
    ind-central      = "Central India"
    ind-south        = "South India"
    asia-south-east  = "Southeast Asia"
    asia-east        = "East Asia"
    cn-east          = "China East"
    cn-east-2        = "China East 2"
    cn-east-3        = "China East 3"
    cn-north         = "China North"
    cn-north-2       = "China North 2"
    cn-north-3       = "China North 3"
    kor-central      = "Korea Central"
    kor-south        = "Korea South"
    jap-east         = "Japan East"
    jap-west         = "Japan West"
    aus-central      = "Australia Central"
    aus-central-2    = "Australia Central 2"
    aus-east         = "Australia East"
    aus-south-east   = "Australia Southeast"
    uae-central      = "UAE Central" # United Arab Emirates
    uae-north        = "UAE North"   # United Arab Emirates
    usgov-arizona    = "US Gov Arizona"
    usgov-texas      = "US Gov Texas"
    usgov-iowa       = "US Gov Iowa"
    usgov-virginia   = "US Gov Virginia"
    usdod-east       = "US DoD East"
    usdod-central    = "US DoD Central"


    # Global/continental zones
    asia    = "Asia"                 # Asia
    asia-pa = "Asia Pacific"         # Asia Pacific
    aus     = "Australia"            # Australia
    bra     = "Brazil"               # Brazil
    can     = "Canada"               # Canada
    eu      = "Europe"               # Europe
    fr      = "France"               # France
    ger     = "Germany"              # Germany
    global  = "Global"               # Global
    ind     = "India"                # India
    jap     = "Japan"                # Japan
    kor     = "Korea"                # Korea
    norw    = "Norway"               # Norway
    ""      = "Singapore"            # Singapore
    saf     = "South Africa"         # South Africa
    swz     = "Switzerland"          # Switzerland
    uae     = "United Arab Emirates" # United Arab Emirates
    uk      = "United Kingdom"       # United Kingdom
    us      = "United States"        # United States
    useuap  = "United States EUAP"   # United States EUAP
  }

  geo_short_codes = {
    australiacentral   = "acl"
    australiacentral2  = "acl2"
    australiaeast      = "ae"
    australiasoutheast = "ase"
    brazilsouth        = "bs"
    brazilsoutheast    = "bse"
    centraluseuap      = "ccy"
    canadacentral      = "cnc"
    canadaeast         = "cne"
    centralus          = "cus"
    eastasia           = "ea"
    eastus2euap        = "ecy"
    eastus             = "eus"
    eastus2            = "eus2"
    francecentral      = "frc"
    francesouth        = "frs"
    germanynorth       = "gn"
    germanywestcentral = "gwc"
    centralindia       = "inc"
    southindia         = "ins"
    westindia          = "inw"
    japaneast          = "jpe"
    japanwest          = "jpw"
    jioindiacentral    = "jic"
    jioindiawest       = "jiw"
    koreacentral       = "krc"
    koreasouth         = "krs"
    northcentralus     = "ncus"
    northeurope        = "ne"
    norwayeast         = "nwe"
    norwaywest         = "nww"
    qatarcentral       = "qac"
    southafricanorth   = "san"
    southafricawest    = "saw"
    southcentralus     = "scus"
    swedencentral      = "sdc"
    swedensouth        = "sds"
    southeastasia      = "sea"
    switzerlandnorth   = "szn"
    switzerlandwest    = "szw"
    uaecentral         = "uac"
    uaenorth           = "uan"
    uksouth            = "uks"
    ukwest             = "ukw"
    westcentralus      = "wcus"
    westeurope         = "we"
    westus             = "wus"
    westus2            = "wus2"
    westus3            = "wus3"
    usdodcentral       = "udc"
    usdodeast          = "ude"
    usgovarizona       = "uga"
    usgoviowa          = "ugi"
    usgovtexas         = "ugt"
    usgovvirginia      = "ugv"
    usnateast          = "exe"
    usnatwest          = "exw"
    usseceast          = "rxe"
    ussecwest          = "rxw"
    chinanorth         = "bjb"
    chinanorth2        = "bjb2"
    chinanorth3        = "bjb3"
    chinaeast          = "sha"
    chinaeast2         = "sha2"
    chinaeast3         = "sha3"
    germanycentral     = "gec"
    germanynortheast   = "gne"
  }
  cli_names = {
    us-east              = "eastus"              # East US
    us-east-2            = "eastus2"             # East US 2
    us-south-central     = "southcentralus"      # South Central US
    us-west-2            = "westus2"             # West US 2
    us-west-3            = "westus3"             # West US 3
    aus-east             = "australiaeast"       # Australia East
    asia-south-east      = "southeastasia"       # Southeast Asia
    eu-north             = "northeurope"         # North Europe
    swe-central          = "swedencentral"       # Sweden Central
    uk-south             = "uksouth"             # UK South
    eu-west              = "westeurope"          # West Europe
    us-central           = "centralus"           # Central US
    saf-north            = "southafricanorth"    # South Africa North
    ind-central          = "centralindia"        # Central India
    asia-east            = "eastasia"            # East Asia
    jap-east             = "japaneast"           # Japan East
    kor-central          = "koreacentral"        # Korea Central
    can-central          = "canadacentral"       # Canada Central
    fr-central           = "francecentral"       # France Central
    ger-west-central     = "germanywestcentral"  # Germany West Central
    norw-east            = "norwayeast"          # Norway East
    swz-north            = "switzerlandnorth"    # Switzerland North
    uae-north            = "uaenorth"            # UAE North
    bra-south            = "brazilsouth"         # Brazil South
    us-east-2-euap       = "eastus2euap"         # East US 2 EUAP
    ""                   = "qatarcentral"        # Qatar Central
    us-central-stg       = "centralusstage"      # Central US (Stage)
    us-east-stg          = "eastusstage"         # East US (Stage)
    us-east-2-stg        = "eastus2stage"        # East US 2 (Stage)
    us-north-central-stg = "northcentralusstage" # North Central US (Stage)
    us-south-central-stg = "southcentralusstage" # South Central US (Stage)
    us-west-stg          = "westusstage"         # West US (Stage)
    us-west-2-stg        = "westus2stage"        # West US 2 (Stage)
    asia                 = "asia"                # Asia
    asia-pa              = "asiapacific"         # Asia Pacific
    aus                  = "australia"           # Australia
    bra                  = "brazil"              # Brazil
    can                  = "canada"              # Canada
    eu                   = "europe"              # Europe
    fr                   = "france"              # France
    ger                  = "germany"             # Germany
    global               = "global"              # Global
    ind                  = "india"               # India
    jap                  = "japan"               # Japan
    kor                  = "korea"               # Korea
    norw                 = "norway"              # Norway
    ""                   = "singapore"           # Singapore
    saf                  = "southafrica"         # South Africa
    swz                  = "switzerland"         # Switzerland
    uae                  = "uae"                 # United Arab Emirates
    uk                   = "uk"                  # United Kingdom
    us                   = "unitedstates"        # United States
    useuap               = "unitedstateseuap"    # United States EUAP
    asia-east-stg        = "eastasiastage"       # East Asia (Stage)
    asia-south-east-stg  = "southeastasiastage"  # Southeast Asia (Stage)
    us-east-stg          = "eastusstg"           # East US STG
    us-north-central     = "northcentralus"      # North Central US
    us-west              = "westus"              # West US
    ind-jio-west         = "jioindiawest"        # Jio India West
    us-central-euap      = "centraluseuap"       # Central US EUAP
    us-west-central      = "westcentralus"       # West Central US
    saf-west             = "southafricawest"     # South Africa West
    aus-central          = "australiacentral"    # Australia Central
    aus-central-2        = "australiacentral2"   # Australia Central 2
    aus-south-east       = "australiasoutheast"  # Australia Southeast
    jap-west             = "japanwest"           # Japan West
    ind-jio-central      = "jioindiacentral"     # Jio India Central
    kor-south            = "koreasouth"          # Korea South
    ind-south            = "southindia"          # South India
    ind-west             = "westindia"           # West India
    can-east             = "canadaeast"          # Canada East
    fr-south             = "francesouth"         # France South
    ger-north            = "germanynorth"        # Germany North
    norw-west            = "norwaywest"          # Norway West
    swz-west             = "switzerlandwest"     # Switzerland West
    uk-west              = "ukwest"              # UK West
    uae-central          = "uaecentral"          # UAE Central
    bra-south-east       = "brazilsoutheast"     # Brazil Southeast
    ger-north-east       = "germanynortheast"    # "Germany Northeast"
    ger-central          = "germanycentral"      # "Germany Central"

    cn-north   = "chinanorth"  # "China North"
    cn-east    = "chinaeast"   # "China East"
    cn-east-2  = "chinaeast2"  # "China East 2"
    cn-north-2 = "chinanorth2" # "China North 2"
    cn-east-3  = "chinaeast3"  # "China East 3"
    cn-north-3 = "chinanorth3" # "China North 3"
  }

  paired = {
    us-west          = "us-east"
    us-west-2        = "us-west-central"
    us-west-3        = "us-east"
    us-central       = "us-east-2"
    us-west-central  = "us-west-2"
    us-south-central = "us-north-central"
    us-north-central = "us-south-central"
    us-east          = "us-west"
    us-east-2        = "us-central"
    can-central      = "can-east"
    can-east         = "can-central"
    bra-south        = "us-south-central"
    bra-south-east   = "bra-south"
    uk-south         = "uk-west"
    uk-west          = "uk-south"
    eu-north         = "eu-west"
    eu-west          = "eu-north"
    fr-central       = "fr-south"
    fr-south         = "fr-central"
    ger-north        = "ger-west-central"
    ger-west-central = "ger-north"
    swz-north        = "swz-west"
    swz-west         = "swz-north"
    norw-east        = "norw-west"
    norw-west        = "norw-east"
    saf-west         = "saf-north"
    saf-north        = "saf-west"
    ind-west         = "ind-south"
    ind-central      = "ind-south"
    ind-south        = "ind-central"
    asia-south-east  = "asia-east"
    asia-east        = "asia-south-east"
    cn-east          = "cn-north"
    cn-east-2        = "cn-north-2"
    cn-east-3        = "cn-north-3"
    cn-north         = "cn-east"
    cn-north-2       = "cn-east-2"
    cn-north-3       = "cn-east-3"
    kor-central      = "kor-south"
    kor-south        = "kor-central"
    jap-east         = "jap-east"
    jap-west         = "jap-west"
    aus-central      = "aus-central-2"
    aus-central-2    = "aus-central"
    aus-east         = "aus-south-east"
    aus-south-east   = "aus-east"
    swe-central      = "swe-south"
    swe-south        = "swe-central"
    uae-central      = "uae-north"   # United Arab Emirates
    uae-north        = "uae-central" # United Arab Emirates
    usdod-east       = "usdod-central"
    usdod-central    = "usdod-east"
    usgov-arizona    = "usgov-texas"
    usgov-iowa       = "usgov-virginia"
    usgov-virginia   = "usgov-texas"

  }
  paired_region = try(local.paired[local.location_slug], null)
}